#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates 
# itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
i=0
while [ "$i" -eq 0 ]
do
	echo "To infinity and beyond"
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap './siggy' SIGQUIT SIGTERM
done
