#!/usr/bin/env bash
# print "best school" till 9 them also print "Hi"

count=0
while [ "$count" -lt 10 ]
do
	echo "Best School"
	if [ "$count" -eq 8 ]
	then
		echo "Hi"
	fi
	count=$((count + 1))
done
