#!/usr/bin/env bash
# print 1 to 20 for and diaplays
# "bad luck" for the 4th loop
# "good luck" for 8th loop

count=1
while [ "$count" -le 20 ]
do
	case "$count" in
		4)
			echo $count
			echo "bad luck from China"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17)
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	count=$((count + 1))
done
