#!/usr/bin/env bash
# print a clock of 12hrs 59mins

hour=0
min=1
while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	while [ "$min" -le 59 ]
	do
		echo $min
		min=$((min + 1))
	done
	min=1
	hour=$((hour + 1))
done
